[window]
decorations = "None"
opacity = 1.00
blur = true
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
padding = { x = 0, y = 0 }

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[colors]
primary.background = "#272727"

[font]
size = 17.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
